### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by manuelfink** [NagRock/ngx-auto-scroll#4] opened 2017-03-18 15:09 UTC
Just dried it on an div with height 500px. Does not work for me at all, neither it throws any errors :/

**Comment by NagRock** [comment] 2017-03-18 15:34
Can you show code your code?

18 mar 2017 4:09 PM "Manuel Fink" <notifications@github.com> napisał(a):

Just dried it on an div with height 500px. Does not work for me at all,
neither it throws any errors :/

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NagRock/angular2-auto-scroll/issues/4>, or mute the
thread

**Comment by NagRock** [comment] 2017-03-29 06:05
Closing as cannot reproduce. Please reopen it with example code if it is still not working.

**Closed as completed by NagRock** 2017-03-29 06:05 UTC
